export const DALOA_ZONES = [
  // Très cités (5+)
  'Abattoir',
  'Orly',
  'Lobia',
  'Kennedy',
  'Soleil',
  'Texas',
  'Tazibouo',
  'Huberson',
  'Labia',
  'Millionnaire',
  'Fadiga',
  'Marin',
  'Cissoko',
  'Évêché',
  'Garage',
  'Gbeulville',
  'Suisse',
  // Cités (2-4)
  'Balouzon',
  'Belle-ville',
  'Commerce',
  'Dioulabougou',
  'Quartier Baoulé',
  'Cafop',
  'Koyakabougou',
  'Liberia',
  'Manioc',
  'Mossibougou',
  'Sapia',
  'Savonnerie',
  'Wolof',
  // Peu cités (1)
  'Àhoussabougou',
  'Batar',
  'Belle Côte',
  'Brésil',
  'Cité Verte',
  'Cocotier',
  'Corridor',
  'Gbokora',
  'Hodjinninkloni',
  'Houssoukro',
  'Institut Pastoral',
  'Jacqueville',
  'Koutoukou',
  'Mines',
  'Monshibougou',
  'Palmeraie',
  'Parlement',
  'Penarole',
  'Petit Paris',
  'Pointé',
  'Seryville',
  'Soweto',
  'Tagoura',
  'Tapeguhe',
  'Wata',
  'Yêmakônô',
  'Zèguéguia',
].sort((a, b) => a.localeCompare(b)); // Sort alphabetically for easier searching
